<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-25T19:40:07 IST" name="Suite" finished-at="2024-12-25T19:40:26 IST" duration-ms="19298">
    <groups>
    </groups>
    <test started-at="2024-12-25T19:40:07 IST" name="Test" finished-at="2024-12-25T19:40:26 IST" duration-ms="19298">
      <class name="StanAloneTest">
        <test-method signature="SubmitOrder()[pri:0, instance:StanAloneTest@cecf639]" started-at="2024-12-25T19:40:07 IST" name="SubmitOrder" finished-at="2024-12-25T19:40:26 IST" duration-ms="19081" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null
at config.TestListeners.onTestSuccess(TestListeners.java:23)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:119)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:285)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:774)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:StanAloneTest@cecf639]" started-at="2024-12-25T19:40:07 IST" name="launchApplication" finished-at="2024-12-25T19:40:11 IST" duration-ms="4564" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
      </class> <!-- StanAloneTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
